matrix:
  include:
  - os: linux
    dist: xenial
    language: minimal
    services:
    - docker
    env:
    - OS_NAME: linux
script:
- ./build.sh _travis-${TRAVIS_OS_NAME}
- ./scripts/travis_test.sh
