# android checks whether we can build for Android
name: android
on:
  push:
    branches:
      - "release/**"
      - "fix/mkupdates"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./mk OONI_PSIPHON_TAGS="" ./MOBILE/android/oonimkall.aar
