name: android
on:
  push:
    branches:
      - mobile-staging
      - "release/**"
      - "*android*"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: brew install --cask android-sdk
      - run: echo y | sdkmanager --install "platforms;android-29"
      - run: echo y | sdkmanager --install "ndk-bundle"
      - run: ./build-android.bash
        env:
          ANDROID_HOME: /usr/local/Caskroom/android-sdk/4333796
      - run: ./publish-android.bash
        env:
          MOBILE_BINTRAY_API_KEY: ${{ secrets.MOBILE_BINTRAY_API_KEY }}
