name: cli
on:
  push:
  schedule:
    - cron: "14 17 * * 3"
jobs:

  # Build all the binaries using macOS
  build:
    runs-on: "macos-latest"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: brew update
      - run: brew install mingw-w64
      - run: ./build.sh release
      - uses: actions/upload-artifact@v1
        with:
          name: ooniprobe-linux-amd64
          path: ./CLI/linux/amd64/ooniprobe
      - uses: actions/upload-artifact@v1
        with:
          name: ooniprobe-macos-amd64
          path: ./CLI/macos/amd64/ooniprobe
      - uses: actions/upload-artifact@v1
        with:
          name: ooniprobe-windows-amd64
          path: ./CLI/windows/amd64/ooniprobe.exe

  # Tests the Linux binary
  linux_test:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ooniprobe-linux-amd64
          path: ooniprobe
      - run: ./smoketest.sh

  # Test binary for macOS
  macos_test:
    needs: build
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ooniprobe-macos-amd64
          path: ooniprobe
      - run: ./smoketest.sh

  # Test binary for Windows
  windows_test:
    needs: build
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ooniprobe-windows-amd64
          path: ooniprobe.exe
      - run: bash ./smoketest.sh