# Cross compile Windows binary from Debian
name: cross-windows-linux
on: [push]
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: sudo apt install --yes mingw-w64
      - run: go build -tags netgo -ldflags='-s -w' ./cmd/ooniprobe
        env:
          CC: x86_64-w64-mingw32-gcc
          CGO_ENABLED: 1
          GOARCH: amd64
          GOOS: windows
