---
# Build and publish Debian packages
name: debian
on:
  push:
    branches:
      - "master"
      - "release/**"
      - "issue/1466"
    tags:
      - "v*"
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Docker
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - run: ./make --disable-embedding-psiphon-config debian_amd64
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - run: sudo apt-get update -q
      - name: Install deps
        run: sudo apt-get install -y --no-install-recommends git python3 python3-requests python3-gnupg s3cmd
      - name: Sign and upload
        run: |
          for deb in *.deb; do
            # AWS user debci-s3
            ./.github/workflows/debops-ci --show-commands upload --bucket-name ooni-deb $deb
          done
        env:
          DEB_GPG_KEY: ${{ secrets.DEB_GPG_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
