---
# Build and publish Debian packages
name: debian
on:
  push:
    branches:
      - "master"
      - "release/**"
      - "issue/1466"
    tags:
      - "v*"
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: enable experimental docker features
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: update debian packages
        run: sudo apt-get update -q
      - name: install qemu-user-static
        run: sudo apt-get install qemu-user-static
      - name: package ooniprobe for debian
        run: ./make --disable-embedding-psiphon-config -t debian
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: install debops-ci dependencies
        run: sudo apt-get install -y --no-install-recommends git python3 python3-requests python3-gnupg s3cmd
      - name: sign packages and upload with debops-ci
        run: |
          for deb in *.deb; do
            # AWS user debci-s3
            ./.github/workflows/debops-ci --show-commands upload        \
                                          --bucket-name ooni-deb $deb
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEB_GPG_KEY: ${{ secrets.DEB_GPG_KEY }}
