# e2eminiooni runs end-to-end tests using miniooni
name: "e2eminiooni"
on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: ./E2E/miniooni.bash
