# ios checks whether we can build for iOS
name: ios
on:
  push:
    branches:
      - "release/**"
      - "fix/mkupdates"
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16.4"
      - uses: actions/checkout@v2
      - run: ./mk OONI_PSIPHON_TAGS="" ./MOBILE/ios/oonimkall.framework.zip
