name: linux
on:
  push:
  pull_request:
  schedule:
    - cron: "14 17 * * 3"
jobs:
  test:
    runs-on: "ubuntu-latest"
    container:
      image: "golang:1.14-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: apk add --no-progress gcc git linux-headers musl-dev
      - run: ./build.sh linux
      - run: ./smoketest.sh linux
      - uses: actions/upload-artifact@v1
        with:
          name: ooniprobe-linux-amd64
          path: ./dist/linux/amd64/ooniprobe
