# linux builds ooniprobe for Linux
name: linux
on:
  pull_request:
  push:
    branches:
      - "release/**"
    tags:
      - "v*"
jobs:

  build_amd64:
    runs-on: "ubuntu-20.04"
    steps:
      - run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - run: ./make --disable-embedding-psiphon-config -t ./CLI/linux/amd64/ooniprobe
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - run: ./smoketest.sh ./CLI/linux/amd64/ooniprobe
      - run: ./make --disable-embedding-psiphon-config -t debian_amd64
      - run: sudo apt-get install -y --no-install-recommends git python3 python3-requests python3-gnupg s3cmd
      - run: |
          for deb in *.deb; do
            ./.github/workflows/debops-ci --show-commands upload --bucket-name ooni-deb $deb
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEB_GPG_KEY: ${{ secrets.DEB_GPG_KEY }}

  build_arm64:
    runs-on: "ubuntu-20.04"
    steps:
      - run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - run: sudo apt-get install qemu-user-static
      - run: ./make --disable-embedding-psiphon-config -t ./CLI/linux/arm64/ooniprobe
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - run: ./smoketest.sh ./CLI/linux/arm64/ooniprobe
      - run: ./make --disable-embedding-psiphon-config -t debian_arm64
      - run: sudo apt-get install -y --no-install-recommends git python3 python3-requests python3-gnupg s3cmd
      - run: |
          for deb in *.deb; do
            ./.github/workflows/debops-ci --show-commands upload --bucket-name ooni-deb $deb
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEB_GPG_KEY: ${{ secrets.DEB_GPG_KEY }}
