# linux builds ooniprobe for Linux
name: linux
on:
  push:
    branches:
      - "release/**"
jobs:

  build_amd64:
    runs-on: "ubuntu-20.04"
    steps:
      - run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - run: ./make --disable-embedding-psiphon-config -t ./CLI/linux/amd64/ooniprobe
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - run: ./smoketest.sh ./CLI/linux/amd64/ooniprobe
      - run: ./make --disable-embedding-psiphon-config -t debian_amd64

  build_arm64:
    runs-on: "ubuntu-20.04"
    steps:
      - run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - run: sudo apt-get install qemu-user-static
      - run: ./make --disable-embedding-psiphon-config -t ./CLI/linux/arm64/ooniprobe
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - run: ./smoketest.sh ./CLI/linux/arm64/ooniprobe
      - run: ./make --disable-embedding-psiphon-config -t debian_arm64
