# Build and test macOS binary
name: macos
on:
  pull_request:
  push:
    branches:
      - "release/**"
jobs:
  build:
    runs-on: "macos-10.15"
    steps:
      - uses: actions/checkout@v2
      - run: ./make --disable-embedding-psiphon-config ./CLI/darwin/amd64/ooniprobe
      - run: ./smoketest.sh ./CLI/darwin/amd64/ooniprobe
