# shorttests only runs the short tests
name: shorttests
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ "1.16" ]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "${{ matrix.go }}"
      - uses: actions/checkout@v2
      - run: go test -short -race -tags shaping ./...
