# windows builds ooniprobe for Windows
name: windows
on:
  push:
    branches:
      - "release/**"
      - "fix/mkupdates"
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install mingw-w64
      - run: ./mk OONI_PSIPHON_TAGS="" ./CLI/windows/amd64/ooniprobe.exe
      - uses: actions/upload-artifact@v2
        with:
          name: ooniprobe.exe
          path: ./CLI/windows/amd64/ooniprobe.exe
  test:
    needs: build
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ooniprobe.exe
      - run: bash.exe ./smoketest.sh ./ooniprobe.exe
