# Compile a binary for Windows
name: windows
on:
  push:
  schedule:
    - cron: "14 17 * * 3"
jobs:
  test:
    runs-on: "windows-latest"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      # Note! the following line _assumes_ you have a working C compiler. The
      # runner used by GitHub Action uses Mingw-w64, installed by default.
      - run: go build -x -ldflags='-s -w' ./cmd/ooniprobe
      - run: ./ooniprobe.exe onboard --yes
      # Important! DO NOT run performance from CI b/c it will overload m-lab servers
      - run: ./ooniprobe.exe run websites --config testdata/testing-config.json -v --no-collector
      - uses: actions/upload-artifact@v1
        with:
          name: ooniprobe-windows-amd64
          path: ooniprobe.exe
