# windows builds ooniprobe for Windows
name: windows
on:
  pull_request:
  push:
    branches:
      - "release/**"
jobs:
  build:
    runs-on: "windows-2019"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: bash.exe ./build.sh windows_amd64  # TODO(bassosimone): make windows_386 work
      - run: bash.exe ./smoketest.sh ./CLI/windows/amd64/ooniprobe.exe
